-- Целевая схема PostgreSQL для постоянного экспорта — зеркало
-- engine/db/schema.sql (источник истины колонок), контракт: план.md §13.4.
--
-- Типы переведены с SQLite: REAL → double precision, INTEGER → bigint,
-- TEXT → text. Время — unix-секунды (double precision), как и в schema.sql.
--
-- Внешних ключей сознательно НЕТ: экспорт идёт упорядоченным потоком
-- (сначала снимки справочников, потом append-таблицы, план.md §9.3), поэтому
-- ссылки (proxy_id, profile_id, worker_id) уже существуют к моменту вставки —
-- FK избыточны, а PG-зеркало является выгрузкой, а не операционной БД.
--
-- created_at ставится в DEFAULT, чтобы никто не мог забыть его проставить.
-- Всё исполняется docker-entrypoint-initdb.d только при первом создании тома
-- export-pgdata: изменения схемы в работающей БД = docker compose down -v
-- или ручные ALTER.


-- Прокси. username/password хранятся в SQLite, но в PG экспортируются всегда
-- NULL: колонки оставлены ради совместимости схемы, секреты не покидают машину.
CREATE TABLE IF NOT EXISTS proxies (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label           text,
    scheme          text    NOT NULL DEFAULT 'http',
    host            text    NOT NULL,
    port            bigint  NOT NULL,
    username        text,
    password        text,
    latency_ms      bigint,
    is_alive        bigint  NOT NULL DEFAULT 1,
    fail_count      bigint  NOT NULL DEFAULT 0,
    last_checked_at double precision,
    last_error      text,
    created_at      double precision NOT NULL DEFAULT (EXTRACT(EPOCH FROM now())),
    UNIQUE (host, port, username)
);

-- Аккаунты/ключи, с которыми работает кликер.
-- key_ref — ссылка на ключ в hooks.py, сам ключ в БД не хранится;
-- fields — произвольные поля профиля в JSON (тот же формат, что у logs.fields).
CREATE TABLE IF NOT EXISTS profiles (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         text    NOT NULL UNIQUE,
    key_ref      text,
    proxy_id     bigint,
    user_agent   text,
    locale       text,
    timezone     text,
    status       text    NOT NULL DEFAULT 'free',
    last_used_at double precision,
    fields       text    NOT NULL DEFAULT '{}',
    created_at   double precision NOT NULL DEFAULT (EXTRACT(EPOCH FROM now()))
);

-- Воркеры — по одному на браузер (id — технический PK, browser_id — бизнес-ключ).
CREATE TABLE IF NOT EXISTS workers (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pid           bigint,
    browser_id    text    NOT NULL UNIQUE,
    profile_id    bigint,
    proxy_id      bigint,
    status        text    NOT NULL DEFAULT 'starting',
    started_at    double precision,
    heartbeat_at  double precision,
    restart_count bigint  NOT NULL DEFAULT 0,
    last_error    text,
    created_at    double precision NOT NULL DEFAULT (EXTRACT(EPOCH FROM now()))
);

-- Один запуск сценария воркером.
-- status='running' — «живая» строка: её ended_at дописывается повторным
-- upsert'ом уже после того, как строка прошла курсор (план.md §9.3).
CREATE TABLE IF NOT EXISTS runs (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    worker_id      bigint,
    started_at     double precision,
    ended_at       double precision,
    status         text    NOT NULL DEFAULT 'running',
    error          text,
    total_clicks   bigint  NOT NULL DEFAULT 0,
    captcha_seen   bigint  NOT NULL DEFAULT 0,
    captcha_solved bigint  NOT NULL DEFAULT 0,
    created_at     double precision NOT NULL DEFAULT (EXTRACT(EPOCH FROM now()))
);

-- Агрегаты дашборда, наполняются по bucket (unix-секунды начала часа).
CREATE TABLE IF NOT EXISTS metrics_hourly (
    bucket         bigint PRIMARY KEY,
    successes      bigint NOT NULL DEFAULT 0,
    failures       bigint NOT NULL DEFAULT 0,
    requests       bigint NOT NULL DEFAULT 0,
    captchas       bigint NOT NULL DEFAULT 0,
    uptime_seconds bigint NOT NULL DEFAULT 0
);

-- Структурированные логи: message читаем человеком, fields — всё машинное в JSON.
-- day — локальная дата ts (YYYY-MM-DD), DEFAULT нет (как в schema.sql).
CREATE TABLE IF NOT EXISTS logs (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts         double precision NOT NULL,
    day        text,
    level      text    NOT NULL DEFAULT 'INFO',
    browser_id text,
    category   text,
    message    text    NOT NULL,
    fields     text,
    created_at double precision NOT NULL DEFAULT (EXTRACT(EPOCH FROM now()))
);

-- Клики. Заменяет clicklogs.db из legacy-кода.
CREATE TABLE IF NOT EXISTS clicks (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts          double precision NOT NULL,
    url         text    NOT NULL,
    query       text,
    category    text,
    browser_id  text,
    proxy_id    bigint,
    http_status bigint,
    created_at  double precision NOT NULL DEFAULT (EXTRACT(EPOCH FROM now()))
);

-- Источник метрики "запросы/час" через CDP-события, а не по кликам.
CREATE TABLE IF NOT EXISTS network_requests (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts            double precision NOT NULL,
    browser_id    text,
    method        text,
    url           text,
    resource_type text,
    status        bigint,
    created_at    double precision NOT NULL DEFAULT (EXTRACT(EPOCH FROM now()))
);

-- События капчи.
CREATE TABLE IF NOT EXISTS captcha_events (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts              double precision NOT NULL,
    browser_id      text,
    proxy_id        bigint,
    page_url        text,
    sitekey         text,
    screenshot_path text,
    solved          bigint  NOT NULL DEFAULT 0,
    solver          text,
    elapsed_ms      bigint,
    created_at      double precision NOT NULL DEFAULT (EXTRACT(EPOCH FROM now()))
);

-- Выдачи прокси.
CREATE TABLE IF NOT EXISTS proxy_usage (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts         double precision NOT NULL,
    proxy_id   bigint,
    browser_id text,
    result     text,
    latency_ms bigint,
    created_at double precision NOT NULL DEFAULT (EXTRACT(EPOCH FROM now()))
);

-- Снимок отпечатка и окружения сессии для разбора расхождений с антиботом.
CREATE TABLE IF NOT EXISTS diagnostics (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts              double precision NOT NULL,
    browser_id      text,
    proxy_id        bigint,
    ip              text,
    country         text,
    user_agent      text,
    accept_language text,
    timezone_id     text,
    screen_w        bigint,
    screen_h        bigint,
    platform        text,
    webgl_vendor    text,
    webgl_renderer  text,
    browser_version text,
    headers         text,
    suspicion_flags text,
    created_at      double precision NOT NULL DEFAULT (EXTRACT(EPOCH FROM now()))
);

-- Курсоры инкрементального экспорта (план.md §9.2): last_id — максимальный
-- перенесённый id, updated_at — время последнего успешного тика (unix-секунды).
-- Курсор двигается ТОЛЬКО после успешного upsert батча.
CREATE TABLE IF NOT EXISTS export_state (
    table_name  text PRIMARY KEY,
    last_id     bigint NOT NULL DEFAULT 0,
    updated_at  double precision NOT NULL DEFAULT 0
);


-- Индексы — по аналогии с schema.sql: выборки UI/retention по времени
-- и по browser_id, плюс служебные фильтры воркеров/прокси.
CREATE INDEX IF NOT EXISTS idx_logs_ts             ON logs (ts);
CREATE INDEX IF NOT EXISTS idx_logs_browser_id     ON logs (browser_id);
-- Дневной экспорт и retention: выборки по дню с уровнем и воркером.
CREATE INDEX IF NOT EXISTS idx_logs_day_level_browser ON logs (day, level, browser_id);
CREATE INDEX IF NOT EXISTS idx_clicks_ts           ON clicks (ts);
CREATE INDEX IF NOT EXISTS idx_clicks_browser_id   ON clicks (browser_id);
CREATE INDEX IF NOT EXISTS idx_captcha_events_ts   ON captcha_events (ts);
CREATE INDEX IF NOT EXISTS idx_proxy_usage_ts      ON proxy_usage (ts);
CREATE INDEX IF NOT EXISTS idx_diagnostics_ts      ON diagnostics (ts);

CREATE INDEX IF NOT EXISTS idx_network_requests_ts        ON network_requests (ts);
CREATE INDEX IF NOT EXISTS idx_network_requests_browser  ON network_requests (browser_id);

CREATE INDEX IF NOT EXISTS idx_runs_worker_id    ON runs (worker_id);
CREATE INDEX IF NOT EXISTS idx_workers_status    ON workers (status);
CREATE INDEX IF NOT EXISTS idx_workers_heartbeat ON workers (heartbeat_at);
CREATE INDEX IF NOT EXISTS idx_proxies_alive     ON proxies (is_alive);
